### ISSUE TITLE
Unused edm files?

### ISSUE THREAD

**Issue by MarkRivers** [epics-motor/motorSymetrie#2]
@ajgdls I just noticed this directory:

https://github.com/epics-motor/motorSymetrie/tree/main/iocs/hexapod-demo/hexapodDemoApp/opi/edl

It appears to have edm screens for the motor record.  Am I correct in assuming that this directory does not actually work with the current support, and is perhaps a remnant from some other support module?

**Comment by ajgdls** [comment]
Hi @MarkRivers yes I think you are right, that has been pulled in during an early IOC build and does not interact with the current support module.
