### ISSUE TITLE
RELEASE.md refers to configure/RELEASE.local, which doesn't exist

### ISSUE THREAD

**Issue by kmpeters** [epics-motor/motorSymetrie#8]
RELEASE.md refers to configure/RELEASE.local to find out which versions of EPICS modules were used for each release:

https://github.com/epics-motor/motorSymetrie/blob/c7fb548f74055264cd19d03d20415de39355a4d8/RELEASE.md?plain=1#L4-L7

but the RELEASE.local file isn't included in the motorSymetrie module:

https://github.com/epics-motor/motorSymetrie/blob/c7fb548f74055264cd19d03d20415de39355a4d8/.gitignore#L9

Can EPICS module versions be added to RELEASE.md for the current version?

**Comment by MarkRivers** [comment]
I have fixed this by adding configure/RELEASE.local.EXAMPLE and changing RELEASE.md to reference that file.

**Comment by kmpeters** [comment]
Thanks!
